### ISSUE TITLE
Simplify kubernetes locator configuration

### ISSUE THREAD

**Issue by iocanel** [halkyonio/backstage#1]
The current docuemnts performs the following steps which can be ommitted:
1. create service account
2. grab the token of the associate secret
3. populate the token in to the configuration

Instead it is suggested to dynamically read the token from the filesystem ` /var/run/secrets/kubernetes.io/serviceaccount/token` with the use of the `$file` key. For example:

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
  - type: 'config'
    clusters:
      - url: https://kubernetes.default.svc
        name: kind
        authProvider: 'serviceAccount'
        skipTLSVerify: true
        skipMetricsLookup: true
        serviceAccountToken:
          $file: /var/run/secrets/kubernetes.io/serviceaccount/token
```
